In [ ]:
## data -> information -> knowledge

In [ ]:
import pandas as pd

# Sample raw tweet data
data = {
    'tweet_id': [1, 2, 3, 4, 5],
    'tweet': [
        "love the new Spiderverse movie! #film",
        "Login successful at 10:04 PM",
        "That novel blew my mind! #novel",
        "This internship is life-changing #internship",
        "Totally wasted my time on that film... #film"
    ]
}

df = pd.DataFrame(data)
print(df)

   tweet_id                                         tweet
0         1         love the new Spiderverse movie! #film
1         2                  Login successful at 10:04 PM
2         3               That novel blew my mind! #novel
3         4  This internship is life-changing #internship
4         5  Totally wasted my time on that film... #film

- Raw tweet data (DATA stage)

Next step: Let’s filter tweets that contain relevant hashtags to get INFORMATION

In [ ]:
# Filter tweets that contain relevant hashtags: #film, #novel, #internship
hashtags = ['#film', '#novel']
df_info = df[df['tweet'].str.contains('|'.join(hashtags), case=False)]
df_info.reset_index(drop=True, inplace=True)
df_info

   tweet_id                                         tweet
0         1         love the new Spiderverse movie! #film
1         3               That novel blew my mind! #novel
2         5  Totally wasted my time on that film... #film

- We’ve filtered the tweets to only include those with relevant hashtags — this is the INFORMATION stage:

Next: Let’s perform basic sentiment classification (KNOWLEDGE stage) — assigning 1 for positive, 0 for negative based on keywords.

In [ ]:
# Define simple sentiment keywords for demo
positive_keywords = ['love', 'amazing', 'great', 'life-changing', 'blew my mind']
negative_keywords = ['waste', 'wasted', 'bad', 'terrible', 'hate']

def get_sentiment(tweet):
    tweet_lower = tweet.lower()
    if any(word in tweet_lower for word in positive_keywords):
        return 1  # Positive
    elif any(word in tweet_lower for word in negative_keywords):
        return 0  # Negative
    else:
        return None  # Neutral/undefined for this demo

# Apply sentiment analysis
df_info['sentiment'] = df_info['tweet'].apply(get_sentiment)
df_info

<ipython-input-7-13237894>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info['sentiment'] = df_info['tweet'].apply(get_sentiment)

   tweet_id                                         tweet  sentiment
0         1         love the new Spiderverse movie! #film          1
1         3               That novel blew my mind! #novel          1
2         5  Totally wasted my time on that film... #film          0

In [ ]:
##python basics

In [ ]:
#data types

In [ ]:
a = 12    #integer
b = 12.0  #float - decimal
d = True  #boolean - true/false

In [ ]:
type(a)

int

In [ ]:
type(b)

float

In [ ]:
type(d)

bool

In [ ]:
fruits = ["apple", "banana", "mango"]  # List
marks = (85, 90, 95)                   # Tuple
student = {"name": "Bob", "age": 20}   # Dictionary

In [ ]:
students = {
    "Aarav": 19,
    "Diya": 20,
    "Kabir": 18,
    "Anaya": 21,
    "Vivaan": 22
}

In [ ]:
print(students["Anaya"])

21

In [ ]:
print(students["Kabir"])

18

In [ ]:
#combining lists into dict
names = ["Aarav", "Diya", "Kabir", "Anaya", "Vivaan"]
ages = [19, 20, 18, 21, 22]

students = dict(zip(names, ages))

print(students)

{'Aarav': 19, 'Diya': 20, 'Kabir': 18, 'Anaya': 21, 'Vivaan': 22}

In [ ]:
#operators

In [ ]:
##arithmetic

In [ ]:
a = 8
b = 2

In [ ]:
a//b

4

In [ ]:
a%b

0

In [ ]:
a*b

16

In [ ]:
a**b

64

In [ ]:
##relational

In [ ]:
a != b

True

In [ ]:
a == b

False

In [ ]:
h = 20
f = 7
g = 7

In [ ]:
#assignment

In [ ]:
x = 5
y = 3

x += x #x = x + x

In [ ]:
print(x)

10

In [ ]:
x -= y
print(x) #x = x - y
print(y)

SyntaxError: invalid syntax (<ipython-input-17-3522743547>, line 2)

In [ ]:
y -= x
#expression?
print(y)

-7

In [ ]:
##logical

In [ ]:
p = 20
q =  30

In [ ]:
p<q and p==20

True

In [ ]:
p>q or p==20

True

In [ ]:
not(p==20)

False

In [ ]:
#Conditional Statements

In [ ]:
##if statement

In [ ]:
m = 10

if m > 5:
    print("m is greater than 5")

m is greater than 5

In [ ]:
## if...else

In [ ]:
x = 3

if x > 5:
    print("x is greater than 5")
else:
    print("x is NOT greater than 5")

x is NOT greater than 5

In [ ]:
## if..elif..else

In [ ]:
marks = 75

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 60:
    print("Grade: C")
else:
    print("Grade: Fail")

Grade: B

In [ ]:
##ques
x = 10
y = 20

if x > y:
    print("x is greater")
elif x == y:
    print("x and y are equal")
else:
    print("y is greater")

if x + y > 25:
    print("Sum is greater than 25")
else:
    print("Sum is not greater than 25")

y is greater
Sum is greater than 25

In [ ]:
##Loop Structures

In [ ]:
#For loop - range of values

In [ ]:
###range function : built in function

In [ ]:
for i in range(5):
    print("angaar hain!")

angaar hain!
angaar hain!
angaar hain!
angaar hain!
angaar hain!

In [ ]:
#range() - parameters

| Syntax                     | Meaning                                 |
| -------------------------- | --------------------------------------- |
| `range(stop)`              | Starts from 0, ends at `stop - 1`       |
| `range(start, stop)`       | Starts from `start`, ends at `stop - 1` |
| `range(start, stop, step)` | Jump by `step` value                    |

In [ ]:
for i in range(2, 6):
    print(i)

2
3
4
5

In [ ]:
for i in range(1, 10, 2):
  print(i)

1
3
5
7
9

In [ ]:
for i in range(5, 0, -1):
    print(i)

5
4
3
2
1

In [ ]:
#while loop

In [ ]:
x = 1
while x <= 5:
    print(x)
    x += 1

1
2
3
4
5

In [ ]:
#loop control statements

`break`    - Exit the loop **immediately**         
`continue` - **Skip** current round, go next

In [ ]:
for i in range(10):
    if i == 5:
        break
    print(i)

0
1
2
3
4

In [ ]:
for i in range(10):
    if i == 5:
        continue
    print(i)

0
1
2
3
4
6
7
8
9

In [ ]:
##ques
ages = [22, 25, 19, 18, 30, 17, 26]

for age in ages:
    if age < 18:
        break
    print(age)

22
25
19
18
30

In [ ]:
sales = [1000, 2000, 0, 1500, 0, 1800]

for s in sales:
    if s == 0:
        continue
    print(s)

1000
2000
1500
1800

In [ ]:
##User defined Functions

In [ ]:
def addnum(x, y):
  x = x + y
  return x

In [ ]:
addnum(1,9)

10

In [ ]:
##ques
def name(x):
    if (x % 2 == 0):
        print("even")
    else:
        print("odd")

name(9)

odd

In [ ]:
##String formatting

In [ ]:
s = "Angaar Hai"

In [ ]:
#lower case - chnage whole string in lower case
s.lower()

'angaar hai'

In [ ]:
print(s)

Angaar Hai

In [ ]:
#change the whole string to upper case
s.upper()

'ANGAAR HAI'

In [ ]:
s1 = "  this is a statement  "

In [ ]:
s1.strip() #remove whitespace - both ends

'this is a statement'

In [ ]:
s2 = "  data analytics  "

In [ ]:
s2.lstrip() #remove left whitespace

'data analytics  '

In [ ]:
s2.rstrip() #remove right whitespace

'  data analytics'

In [ ]:
s = "Angaar Hai"

In [ ]:
s1 = "  this is a statement  "

In [ ]:
len(s)

10

In [ ]:
len(s1)

23

In [ ]:
s = "Angaar Hai"

In [ ]:
min(s)

' '

In [ ]:
#min(s) = ' ' - whitespace in between is taken in cosnideration

In [ ]:
max(s)

'r'

In [ ]:
s[0]

'A'

In [ ]:
s = "Hello"

In [ ]:
s[2]

'l'

In [ ]:
q = "My Name is Khan. Khan from epiglotis"

In [ ]:
## list of words in our string

In [ ]:
q.split()

['My', 'Name', 'is', 'Khan.', 'Khan', 'from', 'epiglotis']

In [ ]:
#by default - space

In [ ]:
date = "2025-06-12"
date.split("-")

['2025', '06', '12']

In [ ]:
sentence = "Python | SQL | Excel | Power BI"
sentence.split()

['Python', '|', 'SQL', '|', 'Excel', '|', 'Power', 'BI']

In [ ]:
sentence = "Python | SQL | Excel | Power BI"
sentence.split("|")

['Python ', ' SQL ', ' Excel ', ' Power BI']

In [ ]:
sentence = "Python | SQL | Excel | Power BI"
sentence.split(" | ")

['Python', 'SQL', 'Excel', 'Power BI']

In [ ]:
##sometimes we need to replace something

In [ ]:
#replce() - returns string after replacing all occurences of old string with new.

In [ ]:
a = "Bba yolo is great"

In [ ]:
#we want - bba yoda is great

In [ ]:
a = a.replace('yolo', 'yoda') #old, new

In [ ]:
print(a)

Bba yoda is great

In [ ]:
#insert values inside a string dynamically

In [ ]:
name = "abcd" #- 0
age = 28 #- 1

In [ ]:
#print("My name is {} and I am {} years old.")

In [ ]:
print("My name is {} and I am {} years old".format(name, age))  #placeholder

My name is abcd and I am 28 years old

In [ ]:
#Positional Indexing
print("I am {1} years old and my name is {0}.".format(name, age))

I am 28 years old and my name is abcd.

In [ ]:
#Named Placeholders
print("My name is {n} and I am {a} years old.".format(n=name, a=age))

My name is abcd and I am 28 years old.

Why is String Formatting Done?

 1. To make messages dynamic and reusable
 print("My name is abcd and I am 28 years old.")  # hard-coded

 FORMATTING works for any name, any age — dynamic and clean.


 2. Data Reports -
 product = "iPhone"

 price = 89999

 print("Product: {}\nPrice: Rs.{:,}".format(product, price)) - control decimal places, alignment, padding, etc.


 3. inject variables into templates
 user = "Ananya"

 message = f"Welcome back, {user}!"

In [ ]:
##slicing - To get a part (slice) of a string using index numbers

basic syntax:

string[start:stop]

Includes start and Excludes stop

In [ ]:
d = "analytics"

In [ ]:
d[5:8]

'tic'

In [ ]:
#starts from index 5 and goes up to 7 (excludes 8)

In [ ]:
#Omitting start or end:
d[:5]

'analy'

In [ ]:
d[4:]

'ytics'

In [ ]:
d= 'analytics'

In [ ]:
#negative index
d[-3:]

'ics'

In [ ]:
#3rd character from the end - slice till end

In [ ]:
d[:-3]

'analyt'

In [ ]:
#start from 0 - up to 3rd last character, but not including it

In [ ]:
## d[start:stop:step]

In [ ]:
d[::2] #step by 2

'aayis'

In [ ]:
##ques
d[0:5]

'analy'

In [ ]:
d[-4:]

'tics'

In [ ]:
##LISTS

Stores a sequential collection of elements

In [ ]:
l1 = list()
print(l1)

[]

In [ ]:
l2 = list([1,2,3,4])
print(l2)

[1, 2, 3, 4]

In [ ]:
#range function
l3 = list(range(1, 10, 2))
print(l3)

[1, 3, 5, 7, 9]

In [ ]:
l4 = list('names')
print(l4)

['n', 'a', 'm', 'e', 's']

In [ ]:
l1 = [2,3,4,1,32]

In [ ]:
len(l1)

5

In [ ]:
max(l1)

32

In [ ]:
min(l1)

1

In [ ]:
sum(l1)

42

In [ ]:
import random
random.shuffle(l1)
print(l1)

[3, 32, 4, 2, 1]

In [ ]:
l1[1:4]

[32, 4, 2]

In [ ]:
#add things

In [ ]:
l1.append(10)

In [ ]:
l1

[3, 32, 4, 2, 1, 10]

In [ ]:
l2 = ['a', 'b', 'c']
l3 = ['d', 'e', 'f']

In [ ]:
l2.append(l3)

In [ ]:
l2

['a', 'b', 'c', ['d', 'e', 'f']]

In [ ]:
l4 = [2,3,4,5,6,7]
l5 = [1,100,200]

In [ ]:
l4.extend(l5)

In [ ]:
l4

[2, 3, 4, 5, 6, 7, 1, 100, 200]

| Feature              | `append()`                         | `extend()`                              |
| -------------------- | ---------------------------------- | --------------------------------------- |
| Purpose              | **Add a single element**           | **Add multiple elements** (unpack list) |
| Data Structure Added | Adds **as is**                     | Adds **elements individually**          |
| List becomes         | Longer by 1 item (the whole thing) | Longer by number of elements added      |

In [ ]:
l5.insert(3, 45) #index 3 - number 45

In [ ]:
l5

[1, 100, 200, 45]

In [ ]:
l5.insert(1,500)

In [ ]:
l5

[1, 500, 100, 200, 45]

In [ ]:
l6 = [1,2,3,4,5,6,7,8,9,10]

In [ ]:
l6.reverse()

In [ ]:
l6

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [ ]:
l7 = [9,2,5,3,7,0]

In [ ]:
l7.sort()
l7

[0, 2, 3, 5, 7, 9]

In [ ]:
l7.sort(reverse = True)

In [ ]:
l7

[9, 7, 5, 3, 2, 0]

In [ ]:
l8 = [1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1]

In [ ]:
l8.count(1)

11

In [ ]:
l8.count(0)

6

In [ ]:
#15th June 2025

In [ ]:
#f string

string formattting - same thing

dynamic text

In [ ]:
name = "Riya"
print(f"My name is {name}")

In [ ]:
#formatted string - we mention letter f : keyword - showcase it is a formatted string

In [ ]:
a = 10
b = 5
print(f"Sum of {a} and {b} is {a + b}")

Sum of 10 and 5 is 15

In [ ]:
# pop() and remove()

In [ ]:
list1 = list(range(1, 11))

In [ ]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list1.pop(3)

4

In [ ]:
#returns value in mentioned index and deletes it from the list

In [ ]:
list1

[1, 2, 3, 5, 6, 7, 8, 9, 10]

In [ ]:
list2 = list([2,5,7,20,2])

In [ ]:
list2

[2, 5, 7, 20, 2]

In [ ]:
list2.remove(2)

In [ ]:
list2

[5, 7, 20, 2]

In [ ]:
list2.pop(3)

2

In [ ]:
list2

[7, 20]

In [ ]:
list2.remove(5)

In [ ]:
#removes first occurence of element

In [ ]:
list3 = list('helloolllo')

In [ ]:
list3

['h', 'e', 'l', 'l', 'o', 'o', 'l', 'l', 'l', 'o']

In [ ]:
list3.remove('l')

In [ ]:
list3

['h', 'e', 'l', 'o', 'o', 'l', 'l', 'l', 'o']

In [ ]:
list3.pop()

'o'

In [ ]:
##DICTIONARY

container object - stores collection of key and pairs

KEYS - UNIQUE

In [ ]:
d1 = {'1' : 'one', '2 ' : 'two', '3' : 'three'}

In [ ]:
print(d1)

{'1': 'one', '2 ': 'two', '3': 'three'}

In [ ]:
d1[6] = 'six'

In [ ]:
d1

{'1': 'one', '2 ': 'two', '3': 'three', 6: 'six'}

In [ ]:
student = {
    "name": "Ravi",
    "age": 21,
    "course": "Data Analytics"
}

In [ ]:
student

{'name': 'Ravi', 'age': 21, 'course': 'Data Analytics'}

In [ ]:
student['name']

'Ravi'

In [ ]:
student['age']

21

In [ ]:
student.values()

dict_values(['Ravi'])

In [ ]:
student.keys()

dict_keys(['name'])

In [ ]:
student["age"] = 22
print(student)  # 'age' updated

{'name': 'Ravi', 'age': 22, 'course': 'Data Analytics'}

In [ ]:
print(student.get("grade"))

None

In [ ]:
student["Data Analytics"] = []

In [ ]:
student

{'name': 'Ravi', 'Data Analytics': []}

In [ ]:
student = {
    "name": "Ravi",
    "age": 21,
    "course": "Data Analytics"
}

In [ ]:
student

{'name': 'Ravi', 'age': 21, 'course': 'Data Analytics'}

In [ ]:
del student["course"]

In [ ]:
student

{'name': 'Ravi', 'age': 22}

In [ ]:
student.pop("age")

22

In [ ]:
student

{'name': 'Ravi'}

| Function      | Use                                         |
| ------------- | ------------------------------------------- |
| `.keys()`     | Gives list of all keys                      |
| `.values()`   | Gives list of all values                    |
| `.items()`    | Returns list of `(key, value)` tuples       |
| `.get("key")` | Returns value (returns `None` if not found) |
| `.update()`   | Adds/updates multiple key-value pairs       |

In [ ]:
student.items()

dict_items([('name', 'Ravi'), ('age', 21), ('course', 'Data Analytics')])

In [ ]:
student.update({"age": 11, "course": "CSE"})

In [ ]:
student

{'name': 'Ravi', 'age': 11, 'course': 'CSE'}

In [ ]:
student.clear()

In [ ]:
student

{}

In [ ]:
##Create a dictionary with 5 students:
###- Each student should have name and marks
###- Add one more student to it
###- Update marks of one student
###- Print all student names and marks

In [ ]:
students = {
    "student1": {"name": "Riya", "marks": 85},
    "student2": {"name": "Aman", "marks": 90},
    "student3": {"name": "Neha", "marks": 78},
    "student4": {"name": "Raj", "marks": 88},
    "student5": {"name": "Simran", "marks": 92}
}

In [ ]:
students['student6'] =  {"name": "Tanya", "marks": 95}

In [ ]:
students

{'student1': {'name': 'Riya', 'marks': 85},
 'student2': {'name': 'Aman', 'marks': 90},
 'student3': {'name': 'Neha', 'marks': 78},
 'student4': {'name': 'Raj', 'marks': 88},
 'student5': {'name': 'Simran', 'marks': 92},
 'student6': {'name': 'Tanya', 'marks': 95}}

In [ ]:
students['student4']['marks'] = 98

In [ ]:
students

{'student1': {'name': 'Riya', 'marks': 85},
 'student2': {'name': 'Aman', 'marks': 90},
 'student3': {'name': 'xyz', 'marks': 78},
 'student4': {'name': 'Raj', 'marks': 98},
 'student5': {'name': 'Simran', 'marks': 92},
 'student6': {'name': 'Tanya', 'marks': 95}}

In [ ]:
students['student3']['name']="xyz"

In [ ]:
#Print All Student Names and Marks

In [ ]:
for key, info in students.items():
    print(f"{info['name']} scored {info['marks']} marks")

Riya scored 85 marks
Aman scored 90 marks
xyz scored 78 marks
Raj scored 98 marks
Simran scored 92 marks
Tanya scored 95 marks

In [ ]:
data = {
    "student1": {"name": "Alice", "age": 21},
    "student2": {"name": "Bob", "age": 23}
}

In [ ]:
print(data)

{'student1': {'name': 'Alice', 'age': 21}, 'student2': {'name': 'Bob', 'age': 23}}

In [ ]:
# Counting word frequency in a sentence
sentence = "data science is fun and data is powerful"
word_count = {}
for word in sentence.split():
    word_count[word] = word_count.get(word, 0) + 1
print(word_count)

{'data': 2, 'science': 1, 'is': 2, 'fun': 1, 'and': 1, 'powerful': 1}